import { readFileSync, createReadStream } from 'fs'
try {
  const env = readFileSync('.env.local', 'utf8')
  for (const line of env.split('\n')) {
    const m = line.match(/^([^#=]+)=(.*)$/)
    if (m) process.env[m[1].trim()] = m[2].trim().replace(/^["']|["']$/g, '')
  }
} catch {}

import { createClient } from '@sanity/client'
const client = createClient({
  projectId: 'vpwi5zan',
  dataset: 'production',
  apiVersion: '2024-01-01',
  token: process.env.SANITY_API_TOKEN,
  useCdn: false,
})

// ─── QUIZ BANK ────────────────────────────────────────────────────────────────
// correctAnswer maps to the position of the correct option in the listed order (A=1st, B=2nd, C=3rd, D=4th)

const quizBanks = {
  'raci-module-1': {
    questionsToShow: 4,
    questions: [
      {
        questionText: 'What does the acronym RACI stand for?',
        optionA: 'Responsible, Accountable, Consulted, Informed',
        optionB: 'Reliable, Assigned, Consulted, Involved',
        optionC: 'Responsible, Assigned, Coordinated, Informed',
        optionD: 'Reviewed, Accountable, Communicated, Involved',
        correctAnswer: 'A',
        explanation: 'RACI stands for Responsible (who does the work), Accountable (who owns the outcome), Consulted (whose input shapes the work), and Informed (who is kept updated).',
        points: 10,
      },
      {
        questionText: 'RACI is also known as a Responsibility Assignment Matrix.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Not applicable',
        optionD: 'Only in project management',
        correctAnswer: 'A',
        explanation: 'True. RACI is formally known as the Responsibility Assignment Matrix (RAM). The "matrix" refers to the grid format: tasks down the side, people across the top.',
        points: 10,
      },
      {
        questionText: 'Which of the following is a key benefit of using RACI?',
        optionA: 'It replaces the need for project meetings',
        optionB: 'It ensures role clarity and reduces duplication of effort',
        optionC: 'It guarantees project completion on time',
        optionD: 'It removes the need for a project manager',
        correctAnswer: 'B',
        explanation: 'RACI\'s primary benefit is role clarity — everyone knows exactly what is expected of them on a given task. This directly reduces duplicated effort and dropped tasks.',
        points: 10,
      },
      {
        questionText: 'RACI should be used for every task in an organisation, including simple checklists and routine activities.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only for tasks involving more than ten people',
        optionD: 'Only for tasks lasting more than a week',
        correctAnswer: 'B',
        explanation: 'False. RACI is most valuable when multiple people are involved, there are cross-functional dependencies, or stakes are high if something is missed. Simple tasks that fit on a basic checklist do not need a full RACI matrix.',
        points: 10,
      },
      {
        questionText: 'What problem does RACI primarily solve?',
        optionA: 'Budget overruns',
        optionB: 'Role ambiguity and unclear responsibilities',
        optionC: 'Lack of technical skills in a team',
        optionD: 'Poor product quality',
        correctAnswer: 'B',
        explanation: 'RACI exists to solve the clarity problem — not a skills problem, but confusion about who is supposed to do what, who has the final say, and who simply needs to be kept informed.',
        points: 10,
      },
      {
        questionText: 'Read this statement and identify the error: "The RACI model is a rigid, one-time exercise that should be completed at the start of a project and never changed."',
        optionA: 'The word "rigid" should be "flexible"',
        optionB: 'RACI is dynamic and should be reviewed and updated as the project evolves',
        optionC: 'RACI should be completed at the end of a project, not the start',
        optionD: 'There is no mistake in this statement',
        correctAnswer: 'B',
        explanation: 'RACI is a living document. Projects change — scope shifts, team members join and leave, stakeholder needs evolve. A matrix that is never reviewed quietly becomes inaccurate and stops being trusted.',
        points: 10,
      },
      {
        questionText: 'Role ambiguity in a project can lead to duplicated efforts, delayed timelines, and conflict between team members.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only if the team is inexperienced',
        optionD: 'Only in large organisations',
        correctAnswer: 'A',
        explanation: 'True. The four failure modes of role ambiguity are: duplicated effort, dropped tasks, decision paralysis, and conflict. RACI directly addresses all four.',
        points: 10,
      },
      {
        questionText: 'When is it NOT appropriate to use the RACI model?',
        optionA: 'For a complex product launch with multiple teams',
        optionB: 'For a software development project with many stakeholders',
        optionC: 'For simple, routine activities that can be managed with a checklist',
        optionD: 'For a marketing campaign with cross-functional involvement',
        correctAnswer: 'C',
        explanation: 'RACI adds unnecessary process to simple tasks. If a checklist already gives everyone the clarity they need, that is the right tool. Use RACI when tasks involve more than two or three people, have dependencies, or carry high stakes.',
        points: 10,
      },
      {
        questionText: 'Which of the following best describes the purpose of RACI?',
        optionA: 'To track project budgets and timelines',
        optionB: 'To map roles and responsibilities in a clear, visual format',
        optionC: 'To document technical specifications for a project',
        optionD: 'To replace performance management systems',
        correctAnswer: 'B',
        explanation: 'RACI maps who is Responsible, Accountable, Consulted, and Informed for every task — displayed in a matrix that anyone can scan and understand at a glance.',
        points: 10,
      },
    ],
  },

  'raci-module-2': {
    questionsToShow: 4,
    questions: [
      {
        questionText: 'Who is the Responsible person in a RACI matrix?',
        optionA: 'The person who approves the final output',
        optionB: 'The person who executes the work for a task',
        optionC: 'The person who provides expert input',
        optionD: 'The person who receives progress updates',
        correctAnswer: 'B',
        explanation: 'Responsible is about doing. The Responsible person has their hands on the work — writing code, designing materials, drafting documents. They need both the skill and the capacity to complete the task.',
        points: 10,
      },
      {
        questionText: 'It is acceptable to have more than one Accountable person for a single task.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only for tasks lasting more than a month',
        optionD: 'Only if both people are senior leaders',
        correctAnswer: 'B',
        explanation: 'False. Every task must have exactly one Accountable person — not zero, not two. Accountability shared between two people quietly becomes accountability that belongs to nobody.',
        points: 10,
      },
      {
        questionText: 'What is the key difference between Responsible and Accountable?',
        optionA: 'Responsible owns the outcome; Accountable does the work',
        optionB: 'Accountable owns the outcome; Responsible does the work',
        optionC: 'They mean the same thing in RACI',
        optionD: 'Accountable is only assigned to senior leaders',
        correctAnswer: 'B',
        explanation: 'Responsible is about doing. Accountable is about owning. A surgeon is Responsible; the head of surgery, answerable if something goes wrong, is Accountable — even without holding the scalpel.',
        points: 10,
      },
      {
        questionText: 'Read this statement and identify the error: "The Accountable role must always be assigned to the most senior person in the team, regardless of the task."',
        optionA: 'The word "senior" should be "junior"',
        optionB: 'Seniority does not determine Accountability — the right person for the task does, and a junior can be Accountable in some situations',
        optionC: 'The Accountable role should be assigned to the most experienced person only',
        optionD: 'There is no mistake in this statement',
        correctAnswer: 'B',
        explanation: 'Seniority does not determine who is Accountable — the task does. A junior team member can be Accountable for a task while a far more senior colleague is Responsible for doing the work. Accountability is about ownership of an outcome, not hierarchy.',
        points: 10,
      },
      {
        questionText: 'The Consulted role involves people who are kept updated on progress but do not contribute directly to the task.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only for external stakeholders',
        optionD: 'Only for senior management',
        correctAnswer: 'B',
        explanation: 'False. That describes the Informed role, not Consulted. Consulted is a two-way relationship — the person\'s input genuinely shapes how the task gets done. Informed is one-way: they receive updates but their input does not change the work.',
        points: 10,
      },
      {
        questionText: 'Which role should receive two-way communication — their input shapes the task?',
        optionA: 'Informed',
        optionB: 'Accountable',
        optionC: 'Consulted',
        optionD: 'Responsible',
        correctAnswer: 'C',
        explanation: 'Consulted is the two-way role. You ask them something, they respond, and that response influences the outcome. Ignoring their input would be a mistake. Informed is the one-way role — they receive updates only.',
        points: 10,
      },
      {
        questionText: 'In a software project, the Legal Team reviews the contract before launch but does not write any code. Which role best fits?',
        optionA: 'Responsible',
        optionB: 'Accountable',
        optionC: 'Consulted',
        optionD: 'Informed',
        correctAnswer: 'C',
        explanation: 'The Legal Team is Consulted — their expertise shapes how the product is built or launched. Their review is a two-way conversation whose output influences the task, even though they are not doing the work themselves.',
        points: 10,
      },
      {
        questionText: 'Having too many people in the Consulted role can slow down task completion.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only on large projects',
        optionD: 'Only when deadlines are tight',
        correctAnswer: 'A',
        explanation: 'True. Every additional person you consult adds a conversation, a delay, and a chance for conflicting input. Ask honestly: would this task genuinely be worse without this person\'s input? If no, they likely do not need to be Consulted.',
        points: 10,
      },
      {
        questionText: 'The Sales Team is told about a product launch so they can prepare their pitch materials. They have no role in the launch itself. Which RACI role applies?',
        optionA: 'Consulted',
        optionB: 'Accountable',
        optionC: 'Responsible',
        optionD: 'Informed',
        correctAnswer: 'D',
        explanation: 'Informed. They receive a one-way update — the launch is happening, here are the details. If they were actively preparing the launch materials, they would be Responsible for that task. The distinction is whether they are doing something with the information or simply receiving it.',
        points: 10,
      },
      {
        questionText: 'Read this statement and identify the error: "In every RACI matrix, there must be exactly one Responsible and one Accountable for each task. If you find two, the task is fine as it is."',
        optionA: 'The number of Consulted roles is what matters, not Responsible',
        optionB: 'If a task has more than one Responsible or Accountable, the task needs to be broken down further',
        optionC: 'Two Accountable roles are acceptable when both are senior leaders',
        optionD: 'There is no mistake in this statement',
        correctAnswer: 'B',
        explanation: 'If a task has more than one Accountable person, the task should be split into separate tasks, each with its own single Accountable owner. Shared accountability quietly becomes no accountability.',
        points: 10,
      },
    ],
  },

  'raci-module-3': {
    questionsToShow: 4,
    questions: [
      {
        questionText: 'What is the first step in building a RACI matrix?',
        optionA: 'Assigning roles to team members',
        optionB: 'Identifying the tasks and deliverables for the project',
        optionC: 'Creating the matrix grid in a spreadsheet',
        optionD: 'Sending the matrix to all stakeholders',
        correctAnswer: 'B',
        explanation: 'Before you can assign any roles, you need to know exactly what needs to get done. Without a clear list of tasks and deliverables, any role assignments are built on unstable ground.',
        points: 10,
      },
      {
        questionText: 'In a RACI matrix, tasks are listed in rows and team members or stakeholders are listed in columns.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'It depends on the software used',
        optionD: 'Only for projects with fewer than ten people',
        correctAnswer: 'A',
        explanation: 'True. The standard format: tasks down the rows, stakeholders across the columns, with R, A, C, or I in each cell. This visual layout lets anyone scan and understand who does what without reading lengthy explanations.',
        points: 10,
      },
      {
        questionText: 'What tool helps break a project into smaller, manageable tasks before building the RACI matrix?',
        optionA: 'A Gantt chart',
        optionB: 'A Work Breakdown Structure',
        optionC: 'A risk register',
        optionD: 'A communication plan',
        correctAnswer: 'B',
        explanation: 'A Work Breakdown Structure (WBS) decomposes a project hierarchically into smaller and smaller pieces until each piece is small enough to assign clearly to one Responsible person or team.',
        points: 10,
      },
      {
        questionText: 'Read this statement and identify the error: "When creating a RACI matrix, it is best to include every possible task in minute detail so nothing is overlooked."',
        optionA: 'The matrix should include only the Accountable roles, not all tasks',
        optionB: 'Overcomplicating the breakdown overwhelms the team — balance detail with clarity',
        optionC: 'Tasks should only be listed if they have a Responsible person assigned',
        optionD: 'There is no mistake in this statement',
        correctAnswer: 'B',
        explanation: 'Going too granular creates a matrix so large nobody can read it, and the administrative overhead outweighs the clarity. The right level of detail is whatever lets you assign one clear Accountable person to each line.',
        points: 10,
      },
      {
        questionText: 'After creating the RACI matrix, it should be reviewed for gaps and overlaps before finalising.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only if the team is large',
        optionD: 'Only if the project is complex',
        correctAnswer: 'A',
        explanation: 'True. The review step catches the most common errors: multiple Accountable people on one task, tasks with no Responsible person, and overloaded Consulted or Informed columns. A matrix published without this review is like a document published without proofreading.',
        points: 10,
      },
      {
        questionText: 'Which of the following is a pitfall to avoid when building a RACI matrix?',
        optionA: 'Listing all stakeholders in columns',
        optionB: 'Assigning multiple Accountable roles to a single task',
        optionC: 'Using a spreadsheet to create the matrix',
        optionD: 'Reviewing the matrix after creation',
        correctAnswer: 'B',
        explanation: 'Assigning multiple Accountable people to one task is the most common and most damaging error. It creates the illusion of accountability while ensuring nobody truly owns the outcome.',
        points: 10,
      },
      {
        questionText: 'Deliverables are tangible results or outcomes aligned with project goals, and should be included when building the RACI matrix.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only for large-scale projects',
        optionD: 'Only for external-facing deliverables',
        correctAnswer: 'A',
        explanation: 'True. Deliverables — tangible outcomes you can point to — are the building blocks of a RACI matrix. Breaking a project into its deliverables is the first step to identifying the tasks that need role assignments.',
        points: 10,
      },
      {
        questionText: 'What should you do if you find a task with two Accountable roles during the review step?',
        optionA: 'Keep both — shared accountability is encouraged',
        optionB: 'Remove one Accountable and make them Consulted or Responsible as applicable',
        optionC: 'Add more people to balance the load',
        optionD: 'Delete the task from the matrix',
        correctAnswer: 'B',
        explanation: 'A task with two Accountable people is usually a sign the task needs to be split into two separate tasks, each with its own single Accountable owner. If the task genuinely cannot be split, one person keeps Accountable and the other becomes Consulted or Responsible.',
        points: 10,
      },
    ],
  },

  'raci-module-4': {
    questionsToShow: 4,
    questions: [
      {
        questionText: 'What is the key difference between a project and a process?',
        optionA: 'A project is always larger in scope than a process',
        optionB: 'A project has a defined beginning and end; a process is recurring and ongoing',
        optionC: 'A process always involves more people than a project',
        optionD: 'There is no meaningful difference for RACI purposes',
        correctAnswer: 'B',
        explanation: 'Projects finish — a product launch, a website redesign, a restructuring. Processes loop — order fulfilment, monthly reporting, customer onboarding. This distinction changes which RACI tools apply.',
        points: 10,
      },
      {
        questionText: 'A Work Breakdown Structure is generally the best tool for mapping RACI onto a recurring process.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only for processes with fewer than five steps',
        optionD: 'Only for annual processes',
        correctAnswer: 'B',
        explanation: 'False. A WBS assumes a defined finish line — it decomposes work toward completion. A process has no "finish" to decompose toward; it loops. Processes need a swimlane flowchart that represents flow and repeating steps.',
        points: 10,
      },
      {
        questionText: 'What visual tool is best suited for mapping RACI onto a process with multiple functions involved?',
        optionA: 'A Gantt chart',
        optionB: 'A swimlane flowchart',
        optionC: 'A pie chart',
        optionD: 'A single-column to-do list',
        correctAnswer: 'B',
        explanation: 'A swimlane flowchart organises a process into lanes (one per team or function), shows the sequence and flow of work, and makes handoffs — where processes most often break down — immediately visible as arrows crossing between lanes.',
        points: 10,
      },
      {
        questionText: 'In a swimlane flowchart, what does each lane typically represent?',
        optionA: 'A different day of the week',
        optionB: 'A role, team, or function',
        optionC: 'A different project milestone',
        optionD: 'A budget category',
        correctAnswer: 'B',
        explanation: 'Each lane represents a role, team, or function. Process steps are placed within the lane of whoever performs them. Arrows show flow between steps — and when an arrow crosses from one lane to another, that is a handoff.',
        points: 10,
      },
      {
        questionText: 'Read this statement and identify the error: "For a recurring process, it is best to mark RACI roles on every single micro-step, no matter how small, to ensure nothing is missed."',
        optionA: 'Micro-steps should never have RACI roles at all',
        optionB: 'Process RACI usually works better at a macro level — over-granularity creates a maintenance burden and obscures clarity',
        optionC: 'Only the first step of a process needs a RACI role',
        optionD: 'There is no mistake in this statement',
        correctAnswer: 'B',
        explanation: 'Over-granularity in process RACI creates a matrix that is exhausting to maintain and quickly falls out of date. Focus on the major stages of the flow and the handoffs between them, not every individual micro-step.',
        points: 10,
      },
      {
        questionText: 'In a swimlane flowchart, a handoff between two lanes is shown as an arrow crossing from one lane into another.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only for formal handoffs with sign-off',
        optionD: 'Only in digital tools, not hand-drawn charts',
        correctAnswer: 'A',
        explanation: 'True. An arrow crossing from one lane into another is precisely what represents a handoff. This is what makes swimlane flowcharts so valuable for processes — handoffs are where processes most often break down, and the format exposes every one of them at a glance.',
        points: 10,
      },
      {
        questionText: 'What is a process owner most similar to, in RACI terms?',
        optionA: 'The Consulted role at every step of the process',
        optionB: 'The Accountable role at the level of the entire process, not just one step',
        optionC: 'The Informed role for senior leadership only',
        optionD: 'A role that only exists in project environments, not processes',
        correctAnswer: 'B',
        explanation: 'The process owner is Accountable for the process working well overall — its efficiency, quality, and outcomes — even though they are not performing any individual step themselves. This sits above the step-level Accountable assignments.',
        points: 10,
      },
      {
        questionText: 'A process can have people who are Responsible for individual steps as well as one person who is Accountable for the process as a whole.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only in organisations with more than 50 employees',
        optionD: 'Only when the process spans multiple departments',
        correctAnswer: 'A',
        explanation: 'True. Layered accountability is common in process environments. Step-level Responsible assignments keep the work moving day to day, while the process owner — Accountable for the whole — ensures the process continues to work well as circumstances change.',
        points: 10,
      },
      {
        questionText: 'Why did the consultant\'s first attempt fail in the opening story of this module?',
        optionA: 'He did not understand the four RACI roles',
        optionB: 'He tried to apply a project-style tool to a process that had no defined beginning or end',
        optionC: 'He did not involve the team in building the matrix',
        optionD: 'He assigned too many people to the Consulted role',
        correctAnswer: 'B',
        explanation: 'He used a Work Breakdown Structure and a task-list approach — tools designed for project work — on a recurring operational process with no start and end date. The tool did not match the shape of the work.',
        points: 10,
      },
    ],
  },

  'raci-module-5': {
    questionsToShow: 3,
    questions: [
      {
        questionText: 'What is the first step when introducing RACI to a team?',
        optionA: 'Distribute the completed matrix without explanation',
        optionB: 'Educate the team about the four roles and their benefits',
        optionC: 'Assign roles without team input to save time',
        optionD: 'Create the matrix individually and share the final version',
        correctAnswer: 'B',
        explanation: 'Before sharing any specific assignments, walk through the four roles and explain what each means in practice. When people understand the "why" behind a new process, they are far more likely to use it rather than treat it as box-ticking.',
        points: 10,
      },
      {
        questionText: 'Involving the team when building the RACI matrix reduces resistance and improves accuracy.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only if the team has used RACI before',
        optionD: 'Only for teams of more than five people',
        correctAnswer: 'A',
        explanation: 'True. Collaborative building serves two purposes at once: it produces a more accurate matrix (people closest to the work catch errors), and it produces buy-in (people follow agreements they helped shape).',
        points: 10,
      },
      {
        questionText: 'Which of the following tools is most suitable for sharing a RACI matrix in real time with a distributed team?',
        optionA: 'A printed copy pinned to the office noticeboard',
        optionB: 'A PDF sent by email',
        optionC: 'Google Sheets or a project management tool like Asana or Trello',
        optionD: 'A handwritten chart in a notebook',
        correctAnswer: 'C',
        explanation: 'The matrix must be visible and easily checked by anyone, whenever they need it. Shared digital tools let anyone open it and instantly see who owns what — which is what turns a RACI matrix into a living tool rather than a forgotten document.',
        points: 10,
      },
      {
        questionText: 'Read this statement and identify the error: "The best approach is to create the RACI matrix alone as the project manager and share the final version with the team for information only."',
        optionA: 'The project manager should not be involved in building the matrix',
        optionB: 'The matrix should be built collaboratively with team input to ensure accuracy and buy-in',
        optionC: 'The matrix should only be shared with senior leaders, not the whole team',
        optionD: 'There is no mistake in this statement',
        correctAnswer: 'B',
        explanation: 'A RACI matrix that the team has not helped build is, at best, a document. A RACI matrix the team has helped build is a shared agreement people actually follow. Building it alone and emailing it as a finished product is precisely what went wrong in the opening story.',
        points: 10,
      },
      {
        questionText: 'Using complex project management software is always better than a simple spreadsheet for creating a RACI matrix.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only for teams with technical skills',
        optionD: 'Only for projects lasting more than three months',
        correctAnswer: 'B',
        explanation: 'False. The specific tool matters less than the principle: anyone on the project should be able to open it and instantly see who owns what. Heavyweight software for a small, simple project adds more complexity than value.',
        points: 10,
      },
      {
        questionText: 'What is a key pitfall when implementing RACI with a team?',
        optionA: 'Making the matrix accessible to everyone',
        optionB: 'Educating team members on the four roles',
        optionC: 'Not involving the team during matrix creation',
        optionD: 'Reviewing the matrix at project milestones',
        correctAnswer: 'C',
        explanation: 'Not involving the team creates resistance and inaccuracies. People who do the actual work often have a far better sense of realistic role assignments than someone working from the outside looking in — and they are far more likely to follow a matrix they helped shape.',
        points: 10,
      },
      {
        questionText: 'Generic online RACI templates should be used exactly as downloaded without any customisation.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only for standard project types',
        optionD: 'Only if the team is familiar with RACI',
        correctAnswer: 'B',
        explanation: 'False. A template is a starting point, not a finished matrix. The pitfall of using a generic template is applying it exactly as downloaded without adapting it to your actual project — the tasks, stakeholders, and relationships that make your project unique.',
        points: 10,
      },
      {
        questionText: 'Why is it important to make the RACI matrix accessible to all team members?',
        optionA: 'So that everyone can change roles whenever they want',
        optionB: 'It reinforces role clarity and prevents confusion during the project',
        optionC: 'It replaces the need for project status meetings',
        optionD: 'It ensures the project manager has less work to do',
        correctAnswer: 'B',
        explanation: 'When the matrix is easy to check, people actually check it — before a meeting, before starting a task, before reaching out for input. That habit is what makes RACI a living tool rather than a document created once and forgotten.',
        points: 10,
      },
    ],
  },

  'raci-module-6': {
    questionsToShow: 4,
    questions: [
      {
        questionText: 'When should the RACI matrix be reviewed?',
        optionA: 'Only at the start of the project',
        optionB: 'Only when there is a conflict between team members',
        optionC: 'At key milestones or periodic intervals throughout the project',
        optionD: 'When the project is completed',
        correctAnswer: 'C',
        explanation: 'Set a deliberate rhythm — at key project milestones or fixed periodic intervals. For agile teams, reviewing after each sprint works well. Building this into your existing project rhythm makes it far more likely to actually happen.',
        points: 10,
      },
      {
        questionText: 'Skipping regular reviews of the RACI matrix can lead to outdated roles and ineffective project management.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only on long projects',
        optionD: 'Only when team composition changes',
        correctAnswer: 'A',
        explanation: 'True. A matrix that quietly drifts out of step with reality stops being trusted. Once people notice it no longer reflects how the team is actually working, they stop checking it — and all the benefits of role clarity disappear.',
        points: 10,
      },
      {
        questionText: 'A team member raises a concern that the Marketing Team is being consulted too often, slowing decisions. What is the right action?',
        optionA: 'Remove the Marketing Team from the matrix entirely',
        optionB: 'Review their role and consider changing it to Informed for some tasks',
        optionC: 'Add more people to the Consulted column to share the load',
        optionD: 'Ignore the concern and continue with the existing matrix',
        correctAnswer: 'B',
        explanation: 'This is exactly the kind of feedback the review step is designed to surface. Review which tasks genuinely require the Marketing Team\'s input, and downgrade the others from Consulted to Informed — preserving their visibility without slowing every decision.',
        points: 10,
      },
      {
        questionText: 'Read this statement and identify the error: "Once the RACI matrix is working well, there is no need to make any changes — a good matrix stays good forever."',
        optionA: 'The matrix should be changed every week regardless of project status',
        optionB: 'RACI is a dynamic tool and must adapt when the project scope, team, or stakeholders change',
        optionC: 'Only the Accountable roles need to be reviewed over time',
        optionD: 'There is no mistake in this statement',
        correctAnswer: 'B',
        explanation: 'Projects change — scope shifts, new tasks emerge, team members join and leave. A matrix that is never updated becomes misleading. Refinement is not a sign the original matrix was wrong; it is a sign the project is alive and evolving.',
        points: 10,
      },
      {
        questionText: 'Conflicts in RACI often arise when a Consulted person believes they have authority over the outcome.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only in hierarchical organisations',
        optionD: 'Only when the Accountable person is junior',
        correctAnswer: 'A',
        explanation: 'True. The most frequent conflict happens when a Consulted stakeholder pushes back hard when their input is not fully adopted. The fix is a clear conversation reaffirming what Consulted means: their input genuinely matters, but the Accountable person retains the final decision.',
        points: 10,
      },
      {
        questionText: 'Which of the following is NOT a good reason to refine the RACI matrix?',
        optionA: 'New tasks have emerged in the project',
        optionB: 'A team member has left and been replaced',
        optionC: 'The project manager wants to add more people to every column',
        optionD: 'A stakeholder\'s role has changed',
        correctAnswer: 'C',
        explanation: 'Adding more people to every column without a specific reason is exactly the "overloading the matrix over time" pitfall. A matrix that has grown bloated with unnecessary entries loses the clarity that made it valuable. Keep it lean and intentional.',
        points: 10,
      },
      {
        questionText: 'How can the conflict between Consulted and Responsible roles be managed?',
        optionA: 'By removing the Consulted role from the matrix',
        optionB: 'Through periodic review and open communication among stakeholders',
        optionC: 'By giving the Consulted person final decision authority',
        optionD: 'By merging the two roles into one',
        correctAnswer: 'B',
        explanation: 'Periodic review and open communication — rather than rigid rule enforcement — is what resolves RACI conflict well. The Consulted person\'s expertise remains valuable; a clear, calm conversation reaffirms what their role actually means.',
        points: 10,
      },
      {
        questionText: 'Too many people in the Informed column is not a concern — the more informed, the better.',
        optionA: 'True',
        optionB: 'False',
        optionC: 'Only a concern in small teams',
        optionD: 'Only a concern if emails are used for updates',
        correctAnswer: 'B',
        explanation: 'False. Flooding too many people with updates creates noise, and important updates get lost in it. Keep the Informed list to people who genuinely need to know. Over-inclusion in the Informed column is as much a pitfall as over-inclusion in the Consulted column.',
        points: 10,
      },
      {
        questionText: 'What is the recommended maximum number of key steps when breaking down a complex process for a RACI matrix?',
        optionA: '3',
        optionB: '7',
        optionC: '12',
        optionD: '20',
        correctAnswer: 'B',
        explanation: 'Seven is a widely referenced upper bound for keeping a process overview readable and maintainable. Beyond this, the overview starts to resemble a task list rather than a high-level process map — and the clarity benefit of the swimlane format diminishes.',
        points: 10,
      },
    ],
  },
}

// ─── SEED ─────────────────────────────────────────────────────────────────────

async function seed() {
  // 1. Upload images
  console.log('Uploading images...')

  const badgeStream = createReadStream('C:/PGS_KnowledgeAgent/Scripts/Website/Academy/RACI/RACI badge.png')
  const badgeAsset = await client.assets.upload('image', badgeStream, { filename: 'RACI badge.png' })
  console.log('  ✓ Badge uploaded:', badgeAsset._id)

  const coverStream = createReadStream('C:/PGS_KnowledgeAgent/Scripts/Website/Academy/RACI/RACI COUrse Cover.png')
  const coverAsset = await client.assets.upload('image', coverStream, { filename: 'RACI Course Cover.png' })
  console.log('  ✓ Cover uploaded:', coverAsset._id)

  // 2. Patch course with images
  console.log('\nPatching course with images...')
  await client.patch('raci-decoded-course').set({
    badgeImage: { _type: 'image', asset: { _type: 'reference', _ref: badgeAsset._id } },
    coverImage: { _type: 'image', asset: { _type: 'reference', _ref: coverAsset._id } },
  }).commit()
  console.log('  ✓ raci-decoded-course (badgeImage + coverImage)')

  // 3. Patch modules with quiz question banks
  console.log('\nPatching modules with quiz question banks...')
  for (const [moduleId, { questionsToShow, questions }] of Object.entries(quizBanks)) {
    const quizQuestionBank = questions.map((q, i) => ({ ...q, _type: 'quizQuestion', _key: `${moduleId}-q${i + 1}` }))
    await client.patch(moduleId).set({ questionsToShow, quizQuestionBank }).commit()
    console.log(`  ✓ ${moduleId} — ${questions.length} questions, show ${questionsToShow}`)
  }

  console.log('\nAll done. Images uploaded. 54 quiz questions seeded across 6 modules.')
}

seed().catch(err => { console.error(err); process.exit(1) })
