import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'course',
  title: 'Course',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Course Title',
      type: 'string',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title' },
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description',
      type: 'string',
    }),
    defineField({
      name: 'descriptionLine',
      title: 'Certificate Description Line',
      type: 'string',
      description: 'Shown on certificate below course title',
    }),
    defineField({
      name: 'badgeImage',
      title: 'Course Badge Image',
      type: 'image',
      options: { hotspot: true },
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      options: { hotspot: true },
    }),
    defineField({
      name: 'price',
      title: 'Price (INR)',
      type: 'number',
      description: 'Set to 0 for free. Above 0 triggers Razorpay.',
      validation: Rule => Rule.required().min(0),
    }),
    defineField({
      name: 'modules',
      title: 'Modules',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'academyModule' }] }],
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: { list: ['published', 'coming-soon', 'draft'] },
      initialValue: 'coming-soon',
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      description: 'Short tagline shown under the course title, e.g. Build Clarity. Drive Ownership. Eliminate Confusion.',
    }),
    defineField({
      name: 'hasAssignments',
      title: 'Has Assignments',
      type: 'boolean',
      description: 'If true, each module requires an assignment submission before the next module unlocks.',
      initialValue: false,
    }),
    defineField({
      name: 'paidConsultation',
      title: 'Paid Consultation Add-on',
      type: 'object',
      description: 'Optional paid add-on offered after course completion.',
      fields: [
        { name: 'enabled', title: 'Enabled', type: 'boolean', initialValue: false },
        { name: 'title', title: 'Offer Title', type: 'string' },
        { name: 'description', title: 'Offer Description', type: 'text' },
        { name: 'price', title: 'Price (INR, excl. GST)', type: 'number' },
        { name: 'durationMinutes', title: 'Duration (minutes)', type: 'number' },
        { name: 'bookingLink', title: 'Booking Link', type: 'reference', to: [{ type: 'bookingLink' }] },
      ],
    }),
    defineField({
      name: 'discountActive',
      title: 'Discount Active',
      type: 'boolean',
      description: 'Toggle the discount on or off without removing the discount settings',
      initialValue: false,
    }),
    defineField({
      name: 'discountPercent',
      title: 'Discount Percentage',
      type: 'number',
      description: 'e.g. 20 means 20% off. Only applies when Discount Active is on.',
      validation: Rule => Rule.min(1).max(100),
    }),
    defineField({
      name: 'discountReason',
      title: 'Discount Label',
      type: 'string',
      description: 'e.g. "Launch Offer" or "Early Bird Pricing" — shown as a badge on the course page',
    }),
    defineField({
      name: 'discountExpiry',
      title: 'Discount Expiry Date',
      type: 'date',
      description: 'Optional. Shows "Offer ends [date]" on the course page when set.',
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'status', media: 'coverImage' },
  },
})
